version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/nginx/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "[docker] "
      prefix: "[docker] "
