version: '2'
services:  
  nginx_proxy:
    build: ./nginx
    restart: "always"
    container_name: nginx_proxy
    networks:
      - frontend
    ports:
      - "80:80"

#
# [ networks definition ]
#
networks:  
  frontend:
    driver: bridge
